import type { ForumAuthor, ForumCommentDto, ForumPostDto } from '@elevatesde/shared-types';

export interface ForumTag {
  id: string;
  label: string;
}

export const FORUM_TAGS: ForumTag[] = [
  { id: 'system-design', label: 'System Design' },
  { id: 'leetcode', label: 'LeetCode' },
  { id: 'behavioral', label: 'Behavioral' },
  { id: 'offers', label: 'Offers' },
  { id: 'referrals', label: 'Referrals' },
  { id: 'faang', label: 'FAANG' },
  { id: 'startups', label: 'Startups' },
  { id: 'resume', label: 'Resume' },
];

export function getTagLabel(id: string): string {
  return FORUM_TAGS.find((tag) => tag.id === id)?.label ?? id;
}

const AUTHORS = {
  priya: { id: 'u-priya', name: 'Priya Nair', headline: 'SDE II @ fintech' },
  marco: { id: 'u-marco', name: 'Marco Velasquez', headline: 'New grad, 2025' },
  aisha: { id: 'u-aisha', name: 'Aisha Rahman', headline: 'Senior Engineer' },
  daniel: { id: 'u-daniel', name: 'Daniel Okoro', headline: 'Backend @ healthtech' },
  lena: { id: 'u-lena', name: 'Lena Fischer', headline: 'Switching from QA' },
  raj: { id: 'u-raj', name: 'Raj Patel', headline: 'Staff candidate' },
  sofia: { id: 'u-sofia', name: 'Sofia Bianchi', headline: 'Frontend specialist' },
  kenji: { id: 'u-kenji', name: 'Kenji Watanabe', headline: 'Distributed systems' },
} satisfies Record<string, ForumAuthor>;

export const FORUM_POSTS_SEED: ForumPostDto[] = [
  {
    id: 'post-rate-limiter',
    title: 'How would you design a distributed rate limiter for a public API?',
    body: 'Got this in a final round. I went with a token bucket per client in Redis, but the interviewer kept pushing on what happens when a Redis node fails. How do you keep limits consistent without making every request a synchronous cross-region call?',
    tags: ['system-design', 'faang'],
    author: AUTHORS.kenji,
    upvotes: 142,
    hasUpvoted: false,
    replyCount: 3,
    viewCount: 2140,
    createdAt: '2026-06-19T07:40:00.000Z',
  },
  {
    id: 'post-two-pointer-intuition',
    title: 'Finally understood when to reach for two pointers vs sliding window',
    body: 'Sharing the mental model that clicked for me after ~80 problems: sliding window is two pointers where the window is contiguous and you maintain an invariant. If the answer is a subarray/substring, start there. Curious how others frame it.',
    tags: ['leetcode'],
    author: AUTHORS.marco,
    upvotes: 98,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 1503,
    createdAt: '2026-06-19T05:10:00.000Z',
  },
  {
    id: 'post-offer-comparison',
    title: 'Two offers: larger base vs more equity at an earlier-stage startup',
    body: 'Offer A is a big-tech L4 with a strong base and predictable RSUs. Offer B is a Series B startup, lower base but a meaningful equity grant. Both remote. How are people thinking about risk-adjusting the equity here?',
    tags: ['offers', 'startups'],
    author: AUTHORS.lena,
    upvotes: 76,
    hasUpvoted: false,
    replyCount: 4,
    viewCount: 1188,
    createdAt: '2026-06-18T18:25:00.000Z',
  },
  {
    id: 'post-behavioral-failure',
    title: 'Best framework for the "tell me about a time you failed" question?',
    body: 'STAR feels mechanical when I use it for failure stories. The strongest answers I have heard focus on what changed afterward. What structure has actually worked for you in senior loops?',
    tags: ['behavioral'],
    author: AUTHORS.aisha,
    upvotes: 64,
    hasUpvoted: false,
    replyCount: 1,
    viewCount: 902,
    createdAt: '2026-06-18T12:00:00.000Z',
  },
  {
    id: 'post-referral-etiquette',
    title: 'Is it rude to ask for a referral from someone you only met once?',
    body: 'I had a great 20-minute chat with an engineer at a conference. A role just opened on their team. What is the right way to reconnect without being transactional?',
    tags: ['referrals'],
    author: AUTHORS.marco,
    upvotes: 51,
    hasUpvoted: false,
    replyCount: 0,
    viewCount: 740,
    createdAt: '2026-06-18T09:15:00.000Z',
  },
  {
    id: 'post-news-feed',
    title: 'Designing a news feed: pull vs push vs hybrid fan-out',
    body: 'For a feed with celebrity accounts (millions of followers), pure push fan-out on write explodes. The hybrid approach pushes for normal users and pulls for celebrities at read time. How do you decide the follower threshold?',
    tags: ['system-design'],
    author: AUTHORS.raj,
    upvotes: 119,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 1875,
    createdAt: '2026-06-17T20:30:00.000Z',
  },
  {
    id: 'post-dp-patterns',
    title: 'A short list of DP patterns that cover ~90% of interview questions',
    body: '0/1 knapsack, unbounded knapsack, longest common subsequence, longest increasing subsequence, matrix-path, interval DP, and bitmask DP. Map a new problem to one of these before writing code. What would you add?',
    tags: ['leetcode'],
    author: AUTHORS.priya,
    upvotes: 203,
    hasUpvoted: false,
    replyCount: 5,
    viewCount: 3210,
    createdAt: '2026-06-17T14:45:00.000Z',
  },
  {
    id: 'post-negotiation-window',
    title: 'How long can you realistically stall before accepting an exploding offer?',
    body: 'Recruiter gave me 5 business days. I have two other loops finishing next week. What language have you used to extend a deadline without losing the offer?',
    tags: ['offers'],
    author: AUTHORS.daniel,
    upvotes: 88,
    hasUpvoted: false,
    replyCount: 3,
    viewCount: 1340,
    createdAt: '2026-06-16T11:20:00.000Z',
  },
  {
    id: 'post-resume-bullets',
    title: 'Rewrote my resume bullets to lead with impact and got 3x more callbacks',
    body: 'Old: "Responsible for the payments service." New: "Cut payment failure rate 38% by adding idempotent retries, recovering ~$1.2M/yr." Quantify everything. Happy to review a few if people paste theirs.',
    tags: ['resume'],
    author: AUTHORS.sofia,
    upvotes: 167,
    hasUpvoted: false,
    replyCount: 6,
    viewCount: 2890,
    createdAt: '2026-06-16T08:05:00.000Z',
  },
  {
    id: 'post-url-shortener',
    title: 'URL shortener: how do you guarantee unique short codes at scale?',
    body: 'Base62 of an auto-increment ID is simple but leaks volume and is guessable. A counter range service per host avoids coordination on every write. Where do you land between hashing and ID allocation?',
    tags: ['system-design', 'startups'],
    author: AUTHORS.kenji,
    upvotes: 94,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 1602,
    createdAt: '2026-06-15T16:40:00.000Z',
  },
  {
    id: 'post-graph-bfs-dfs',
    title: 'When BFS beats DFS in interviews (and vice versa)',
    body: 'BFS for shortest path in unweighted graphs and level-order traversal. DFS for connectivity, cycle detection, topological order, and anything recursive on trees. Naming the goal first picks the traversal for you.',
    tags: ['leetcode'],
    author: AUTHORS.marco,
    upvotes: 72,
    hasUpvoted: false,
    replyCount: 1,
    viewCount: 1010,
    createdAt: '2026-06-15T10:10:00.000Z',
  },
  {
    id: 'post-onsite-energy',
    title: 'How do you keep energy up across a 5-hour virtual onsite?',
    body: 'By the fourth interview my brain is mush. Looking for practical tips: breaks, snacks, how you reset between rounds, whether you review notes in the gaps.',
    tags: ['behavioral'],
    author: AUTHORS.lena,
    upvotes: 59,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 845,
    createdAt: '2026-06-14T13:55:00.000Z',
  },
  {
    id: 'post-chat-system',
    title: 'Designing WhatsApp-style messaging: delivery receipts and ordering',
    body: 'The hard part is guaranteeing per-conversation ordering with multiple devices. A monotonic sequence number per conversation seems cleaner than wall-clock timestamps. How do you handle a device that was offline for days?',
    tags: ['system-design', 'faang'],
    author: AUTHORS.raj,
    upvotes: 131,
    hasUpvoted: false,
    replyCount: 3,
    viewCount: 2055,
    createdAt: '2026-06-13T19:05:00.000Z',
  },
  {
    id: 'post-tech-screen-nerves',
    title: 'Blanked on a medium I had solved before. How do you recover live?',
    body: 'Froze on a problem I knew. What saved me was narrating my thought process out loud and asking to start from brute force. The interviewer actually engaged. Sharing in case it helps someone.',
    tags: ['leetcode', 'behavioral'],
    author: AUTHORS.daniel,
    upvotes: 84,
    hasUpvoted: false,
    replyCount: 1,
    viewCount: 1224,
    createdAt: '2026-06-12T15:30:00.000Z',
  },
  {
    id: 'post-equity-refresh',
    title: 'Nobody told me about equity refreshers until year two',
    body: 'Initial grants vest over 4 years but most companies add refreshers each year. Worth asking about the refresh philosophy during negotiation, since it changes the long-term picture a lot.',
    tags: ['offers'],
    author: AUTHORS.priya,
    upvotes: 112,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 1760,
    createdAt: '2026-06-11T09:45:00.000Z',
  },
  {
    id: 'post-cold-email',
    title: 'A cold email template that got me 4 referrals out of 10 sends',
    body: 'Short, specific, and easy to say yes to: who I am, one line on why their team, the exact role/req ID, and an attached resume so they can forward it in one click. Make the ask trivial to fulfill.',
    tags: ['referrals', 'resume'],
    author: AUTHORS.sofia,
    upvotes: 145,
    hasUpvoted: false,
    replyCount: 4,
    viewCount: 2410,
    createdAt: '2026-06-10T17:20:00.000Z',
  },
  {
    id: 'post-consistency-models',
    title: 'Explaining eventual vs strong consistency without the jargon',
    body: 'Strong: every read sees the latest write, at the cost of latency and availability. Eventual: reads may lag but the system stays fast and available. Most product features are fine with eventual. Agree?',
    tags: ['system-design'],
    author: AUTHORS.kenji,
    upvotes: 90,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 1430,
    createdAt: '2026-06-09T12:15:00.000Z',
  },
  {
    id: 'post-heap-recognition',
    title: 'Spotting "top K" problems: it is almost always a heap',
    body: 'If the prompt has "k largest", "k closest", "k frequent", or "merge k", reach for a heap of size k. O(n log k) instead of sorting everything. What other keyword-to-structure mappings do you use?',
    tags: ['leetcode'],
    author: AUTHORS.marco,
    upvotes: 78,
    hasUpvoted: false,
    replyCount: 1,
    viewCount: 1180,
    createdAt: '2026-06-08T08:50:00.000Z',
  },
  {
    id: 'post-startup-due-diligence',
    title: 'What to actually ask a startup before accepting (beyond runway)',
    body: 'Runway is table stakes. I also ask about burn multiple, net revenue retention, the last round valuation vs my strike price, and how decisions get made. What is on your list?',
    tags: ['startups', 'offers'],
    author: AUTHORS.aisha,
    upvotes: 103,
    hasUpvoted: false,
    replyCount: 3,
    viewCount: 1690,
    createdAt: '2026-06-07T14:00:00.000Z',
  },
  {
    id: 'post-manager-loop',
    title: 'The hiring-manager round is not a formality at senior levels',
    body: 'I treated it as a culture chat and underperformed. They are evaluating scope, ownership, and how you handle ambiguity. Come with 2-3 stories about driving cross-team outcomes, not just shipping features.',
    tags: ['behavioral', 'faang'],
    author: AUTHORS.raj,
    upvotes: 121,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 1920,
    createdAt: '2026-06-06T10:30:00.000Z',
  },
  {
    id: 'post-cache-invalidation',
    title: 'Cache invalidation strategies that actually held up in interviews',
    body: 'Write-through keeps the cache fresh but adds write latency. Write-back is fast but risky on failure. TTL plus event-based invalidation covered most follow-ups for me. How do you reason about staleness budgets?',
    tags: ['system-design'],
    author: AUTHORS.daniel,
    upvotes: 86,
    hasUpvoted: false,
    replyCount: 1,
    viewCount: 1355,
    createdAt: '2026-06-05T16:10:00.000Z',
  },
  {
    id: 'post-resume-gap',
    title: 'How do you frame a 9-month career gap without overexplaining?',
    body: 'One honest sentence plus what you did to stay sharp (projects, courses, contracting). Most interviewers care far less than candidates fear. Move the conversation to what you can do now.',
    tags: ['resume', 'behavioral'],
    author: AUTHORS.lena,
    upvotes: 69,
    hasUpvoted: false,
    replyCount: 2,
    viewCount: 980,
    createdAt: '2026-06-04T11:40:00.000Z',
  },
  {
    id: 'post-backtracking',
    title: 'Backtracking template that I reuse for permutations, combinations, and subsets',
    body: 'Same skeleton: choose, recurse, un-choose. The only differences are the start index and whether you skip duplicates. Internalizing one template made these problems boring in a good way.',
    tags: ['leetcode'],
    author: AUTHORS.priya,
    upvotes: 95,
    hasUpvoted: false,
    replyCount: 1,
    viewCount: 1490,
    createdAt: '2026-06-03T09:05:00.000Z',
  },
  {
    id: 'post-comp-transparency',
    title: 'Sharing comp openly with peers leveled the negotiation playing field',
    body: 'A small group of us started sharing exact numbers when we get offers. It is uncomfortable at first, but it made everyone negotiate from data instead of fear. Recruiters lose their information edge.',
    tags: ['offers'],
    author: AUTHORS.sofia,
    upvotes: 158,
    hasUpvoted: false,
    replyCount: 3,
    viewCount: 2530,
    createdAt: '2026-06-02T13:25:00.000Z',
  },
];

export const FORUM_COMMENTS_SEED: Record<string, ForumCommentDto[]> = {
  'post-rate-limiter': [
    {
      id: 'c-rl-1',
      postId: 'post-rate-limiter',
      author: AUTHORS.raj,
      body: 'I would not make limits strongly consistent. Use local token buckets per node with periodic reconciliation. A small amount of over-admission on failover is almost always acceptable for a rate limiter.',
      upvotes: 41,
      hasUpvoted: false,
      createdAt: '2026-06-19T08:05:00.000Z',
    },
    {
      id: 'c-rl-2',
      postId: 'post-rate-limiter',
      author: AUTHORS.priya,
      body: 'Redis Cluster with a replica per shard plus a sliding-window-counter Lua script handled the consistency question for me. Mention degradation: if Redis is down, fail open, not closed.',
      upvotes: 28,
      hasUpvoted: false,
      createdAt: '2026-06-19T08:30:00.000Z',
    },
    {
      id: 'c-rl-3',
      postId: 'post-rate-limiter',
      author: AUTHORS.daniel,
      body: 'The framing they probably wanted: state your consistency requirement explicitly, then justify why approximate is fine here. That is the senior signal.',
      upvotes: 19,
      hasUpvoted: false,
      createdAt: '2026-06-19T09:10:00.000Z',
    },
  ],
  'post-dp-patterns': [
    {
      id: 'c-dp-1',
      postId: 'post-dp-patterns',
      author: AUTHORS.kenji,
      body: 'Add "digit DP" for counting problems with constraints on the number itself. Rare, but it shows up at the harder end.',
      upvotes: 22,
      hasUpvoted: false,
      createdAt: '2026-06-17T15:20:00.000Z',
    },
    {
      id: 'c-dp-2',
      postId: 'post-dp-patterns',
      author: AUTHORS.marco,
      body: 'Saving this. The "map to a known pattern before coding" step is exactly what I skip under pressure.',
      upvotes: 14,
      hasUpvoted: false,
      createdAt: '2026-06-17T16:00:00.000Z',
    },
  ],
  'post-resume-bullets': [
    {
      id: 'c-rb-1',
      postId: 'post-resume-bullets',
      author: AUTHORS.lena,
      body: 'The dollar figure is what does it. "Improved performance" means nothing; "cut p99 latency 40%" is a conversation starter.',
      upvotes: 31,
      hasUpvoted: false,
      createdAt: '2026-06-16T09:00:00.000Z',
    },
  ],
};
